### PR TITLE
Fixed #632 : StringIndexOutOfBoundsException

### LINKED ISSUE #632: I click the Antenna Map Viewer at the slide bar and crashed.
Log:
```
FATAL EXCEPTION: AsyncTask #1
com.SecUpwN.AIMSICD E/AndroidRuntime: Process: com.SecUpwN.AIMSICD, PID: 14623
com.SecUpwN.AIMSICD E/AndroidRuntime: java.lang.RuntimeException: An error occured while executing doInBackground()
com.SecUpwN.AIMSICD E/AndroidRuntime:     at android.os.AsyncTask$3.done(AsyncTask.java:304)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:841)
com.SecUpwN.AIMSICD E/AndroidRuntime:  Caused by: java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=3
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.lang.String.startEndAndLength(String.java:588)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.lang.String.substring(String.java:1475)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at com.SecUpwN.AIMSICD.activities.MapViewerOsmDroid.loadOcidMarkersByNetwork(MapViewerOsmDroid.java:574)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at com.SecUpwN.AIMSICD.activities.MapViewerOsmDroid.access$500(MapViewerOsmDroid.java:91)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at com.SecUpwN.AIMSICD.activities.MapViewerOsmDroid$4.doInBackground(MapViewerOsmDroid.java:400)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at com.SecUpwN.AIMSICD.activities.MapViewerOsmDroid$4.doInBackground(MapViewerOsmDroid.java:392)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at android.os.AsyncTask$2.call(AsyncTask.java:292)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
com.SecUpwN.AIMSICD E/AndroidRuntime:     at java.lang.Thread.run(Thread.java:841) 
```

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/28181086-i-click-the-antenna-map-viewer-at-the-slide-bar-and-crashed?utm_campaign=plugin&utm_content=tracker%2F565750&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F565750&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by smarek**
+ Reformatted code
+ Removed unused fields
+ Converted fields to method-global instead of class-global where applicable
+ Fixed Javadoc on `protected void onPostExecute(GeoPoint defaultLoc)`
+ Renamed few variables for more readable code

### CODE REVIEW

File: app/src/main/java/com/SecUpwN/AIMSICD/activities/MapViewerOsmDroid.java [hunk 1]
```diff
@@ -568,17 +562,16 @@ private void loadOcidMarkersByNetwork() {
...
         LinkedList<CellTowerMarker> items = new LinkedList<>();
         String networkOperator = tm.getNetworkOperator();
-        int imcc =0;
-        int imnc =0;
-        if (networkOperator != null) {
-            imcc = Integer.parseInt(networkOperator.substring(0, 3));
-            imnc = Integer.parseInt(networkOperator.substring(3));
+        int currentMmc = 0;
+        int currentMnc = 0;
+        if (networkOperator != null && networkOperator.length() > 3) {
```
Comment (smarek) [inline app/src/main/java/com/SecUpwN/AIMSICD/activities/MapViewerOsmDroid.java]: This is the only change that fixes #632
